#this scenario will be executed if a Pull Request has been approved 
name: pull request approved logic


env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  TARGET_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  SALESFORCE_ORG_ALIAS: ${{ vars.SALESFORCE_ORG_ALIAS }}
  PR_NUMBER: ${{ github.event.number }}



  ACCESS_KEY_SF_DEV: ${{ vars.PLATFORM_USERNAME_GITHUB_VARIABLE_VALUE }}
#depends on the target branch one of the following scenarios will be executed:
on:
  pull_request_review:
    types: [submitted]


jobs:
  push_logic:
    runs-on: ubuntu-latest
    steps:
      - name: Global Step 0. Logger
        run: |
          echo -e "--- Step 1. Output global info for the current pipeline ---\n"
          echo "Event is:"
          echo -e "Pull request\n"
          echo "Pull request source branch is:"
          echo ${{ github.event.pull_request.head.ref }}
          echo -e "\nPull request target branch is:"
          echo ${{ github.event.pull_request.base.ref }}
        
          

#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0



#      - uses: sfdx-actions/setup-sfdx@v1



#      - name: Global step 1. Salesforce CLI version check
#        run: |
#          sudo npm sfdx --version



#      - name: Global Step 2. Salesforce org login
#        run: |
#            chmod +x ./build/login_to_SF_org.sh
#            ./build/login_to_SF_org.sh



#      - name: Global Step 3. Define destructive changes
#        run: |
#          chmod +x ./build/get_destructive_changes.sh
#          ./build/get_destructive_changes.sh



      #Due to the destructive metadata is represented only on the tharget branch
      #workflow will swith to the target branch
      #to perform destructive changes actions

#      - uses: actions/checkout@v3
#        if: ${{ vars.DESTRUCTIVE_CHANGES_PRESENTED == true }} 
#        with:
#          ref: ${{ github.event.pull_request.base.ref }}



#      - name: Global Step 4. Deploy destructive changes without saving
#        run: |
#          chmod +x ./build/deploy_destructive_changes_actions.sh
#          ./build/deploy_destructive_changes_actions.sh



      #After the destructive changes activities workflow should
      #get back to the source branch to perform following steps    
#      - uses: actions/checkout@v3
#        if: ${{ vars.DESTRUCTIVE_CHANGES_PRESENTED == true }} 
#        with:
#          ref: ${{ github.event.pull_request.head.ref }}


  
#      - name: Global Step 5. Deploy metadata to Salesforce org
#        run: |
#          chmod +x ./build/deploy_metadata_to_sf_org.sh
#          ./build/deploy_metadata_to_sf_org.sh



#  merge_branches:
#    needs: push_logic
#    runs-on: ubuntu-latest
#    steps:
#    - name: test
#      run: |
#        curl -L \
#          -X PUT \
#          -H "Accept: application/vnd.github+json" \
#          -H "Authorization: Bearer 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" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          https://api.github.com/repos/ArtBubnov/SalesforceDevOpsPresentation/pulls/${{ github.event.number }}/merge \
#          -d '{"commit_title":"Expand enum","commit_message":"Add a new value to the merge_method enum"}'

#https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER/merge \
#ArtBubnov