#this scenario will be executed in case of creation of a Pull Request 
name: pull request logic

#workflow global variables
env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  TARGET_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  ACCESS_KEY_SF_DEV: ${{ vars.PLATFORM_USERNAME_GITHUB_VARIABLE_VALUE }}
  
on:
  pull_request:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'
    types: [opened, reopened, synchronize]


jobs:
  pre_deploy_logic:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.ref }}
    steps:

    - name: ENV TEST        
      run: |
        echo "ENV TEST ECHO"
        echo ${{ vars.TEST_ENVIRONMENTS_VAR }}
        echo $TARGET_BRANCH_NAME

          





#----------------------------------------------------
      #Login to the target Salesforce org
#      - name: Global Step 2. Salesforce org login
#        run: |
#          chmod +x ./build/login_to_SF_org.sh
#          ./build/login_to_SF_org.sh            


      #Deploy metadata to the target Salesforce org without saving
      #Apex tests execution
#      - name: Global Step 3. Predeploy actions
#        run: |
#          chmod +x ./build/pre_deploy_actions.sh
#          ./build/pre_deploy_actions.sh




#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.ref }}