#this scenario will be executed in case of creation of a Pull Request 
name: pull request logic

#depends on the target branch one of the following scenarios:  
on:
  push:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'


jobs:
  pre_deploy_logic:
    runs-on: ubuntu-latest
    steps:


    - uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - name: Global Step 1. GET DIFF
      run: |
        chmod +x ./build/get_desteuctive_changes.sh
        ./build/get_desteuctive_changes.sh


    - name: GLOB 2. TEST VAR
      run: |
        echo "${{ env.ENV_DESTRUCTIVE_DIFF }}"



#    - name: Global Step 1. GET DIFF
#      run: |
#        DIFF_BRANCH="origin/qa"
#        mapfile -t GET_DESTRUCTIVE_DIFF_ARRAY < <( git diff --name-only --diff-filter=D ${DIFF_BRANCH} force-app/main/default )
#        echo "ENV_DESTRUCTIVE_DIFF=$GET_DESTRUCTIVE_DIFF_ARRAY" >> "$GITHUB_ENV"


#    - name: GLOB 2. TEST VAR
#      run: |
#        echo "${{ env.ENV_DESTRUCTIVE_DIFF }}" # This will output 'yellow'
#        chmod +x ./build/get_desteuctive_changes.sh
#        ./build/get_desteuctive_changes.sh
