#this scenario will be executed in case of creation of a Pull Request 
name: pull request logic

#depends on the target branch one of the following scenarios:  
on:
  push:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'


jobs:
  pre_deploy_logic:
    runs-on: ubuntu-latest
    steps:

    - name: test
      run: |
        DIFF_BRANCH="qa"
        GET_DESTRUCTIVE_DIFF=$(git diff --name-only --diff-filter=D ${DIFF_BRANCH} force-app/main/default)
        echo $GET_DESTRUCTIVE_DIFF




#    - name: Set the value
#      id: step_one
#      run: |
#        echo "action_state=yellow" >> "$GITHUB_ENV"
#    - name: Use the value
#      id: step_two
#      run: |
#
#        echo "${{ env.action_state }}" # This will output 'yellow'