#this scenario will be executed in case of creation of a Pull Request 
name: pull request logic

#depends on the target branch one of the following scenarios:  
on:
  push:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'


jobs:
  pre_deploy_logic:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: dev

      - uses: sfdx-actions/setup-sfdx@v1

      #Check SFDX version
      - name: Global Step 1. SFDX CLI installation
        run: |
          chmod +x ./build/install_dependencies.sh
          ./build/install_dependencies.sh

      - uses: actions/checkout@v3
        with:
          ref: qa

      #Deploy metadata to the target Salesforce org without saving
      #Apex tests execution
      - name: Global Step 3. Predeploy actions
        run: |
          chmod +x ./build/deploy_destructive_changes_to_sf_org.sh
          ./build/deploy_destructive_changes_to_sf_org.sh
          
        env:
            SOURCE_BRANCH_NAME: "dev"
            TARGET_BRANCH_NAME: "qa"